name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'
  pull_request:

  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: ocaml.flatpak
        manifest-path: org.freedesktop.Sdk.Extension.ocaml.yaml
        cache-key: flatpak-builder-${{ github.sha }}
